name: Deploy Chainlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "pydantic<2.0"
        pip install chainlit
        pip install pytest
        pip install -r requirements.txt || echo "No requirements file, skipping."

    - name: Run pytest
      run: pytest
