name: Deploy Chainlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "pydantic<2.0"                # Install pydantic < 2.0
        pip install chainlit                     # Install Chainlit
        pip install openai==0.28                 # Install OpenAI SDK
        pip install tabulate                     # Install tabulate for tables
        pip install -r requirements.txt || echo "No requirements file, skipping."

    # Step 4: Show installed packages (for debugging)
    - name: Show installed Python packages
      run: |
        pip show pydantic
        pip show chainlit
        pip show openai
        pip list

    # Step 5: Run the Chainlit app
    - name: Run Chainlit App
      run: |
        chainlit run app.py --headless --port 8000
