# .github/workflows/deploy.yml
name: Build and Deploy FastAPI App with Docker to GitHub Container Registry

on:
  push:
    branches:
      - main  # Trigger this action when code is pushed to the `main` branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/asterheng/sh/fastapi-app:latest .

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/fastapi-app:latest

    - name: Deploy to server
      run: |
        # Replace with the deployment commands for your server (AWS, etc.)
        echo "Deploying FastAPI container to server..."
