name: Deploy Chainlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "pydantic<2.0"               # Ensure quotes are properly closed
        pip install chainlit
        pip install openai==0.28
        pip install tabulate
        pip install aioresponses
        pip install responses==0.23.1 --no-cache-dir
        pip install -r requirements.txt || echo "No requirements file, skipping."

    # Step 4: Show installed packages (for debugging)
    - name: Show installed Python packages
      run: pip list

    # Step 5: Run the Chainlit app
    - name: Run Chainlit App
      run: python -m chainlit run app.py --headless --port 8000
